Dev survival
lca1/medco-connector pull request #28
Opened 2020-09-09 09:33 UTC by nfreundl

Survival analysis feature enabled.

Genomic annotations DB renamed medcoconnector. It contains two schemata: genomic_annotations and query_tools. The latter is a new schemas that stores tables to save results of MedCo Explore query and user-defined exploration cohort.

2020-09-15 15:43 UTC, mickmis requested changes
Hey Nicolas, thanks for the PR.

I've done the review in 2 times, so some comments are part of this review, some others are independent comments.

In general I think some additional effort is needed. In addition to the comments made in the code, here are some things that apply for everything:
- Ensure go fmt and golint passes. Unfortunately at the moment the github automated checks are not ran. We will fix this at some point. In the meantime, we need to ensure manually they pass.
- Your code is not well integrated in the existing code base. I've made a number of suggestions to reorganize it. There are also at several places some duplicated code, as a general rule, this should not happen.
- Be consistent in creating errors, it should be with `fmt.Errorf(...)`. Note that this is not everywhere the case in the existing codebase, it is in the backlog to do a pass to update it though.
- All public functions need a documenting comment in the form of "// FunctionName does blabla`. Go fmt or golint should give you an error about it.
- In general some more logging is needed. At the runtime we need to be aware of what is happening. This helps a lot in pinpointing problems when they occur.
- I find the overall flow of the execution not clear. Either make it clear through the code directly, or add a README in `server/survivalanalysis` to make it more clear.
- There is inconsistency in file naming: you should not be using camel case. Use snake case.

2020-09-15 15:43 UTC, mickmis commented on wrappers/unlynx/util.go
> +func NewUnlynxClient() (unlynxClient *servicesmedco.API, cothorityRoster *onet.Roster) {
This should stay private to the package.

2020-09-15 15:43 UTC, mickmis commented on wrappers/i2b2/query_test.go
> +	results, err := GetOntologyTermInfo("/SPHN/SPHNv2020.1/FophDiagnosis/")
This seems to be a query made to specific data, that is not part of the default data loaded with the dev-local-3nodes, while it should be.

2020-09-15 15:43 UTC, mickmis commented on wrappers/i2b2/ontology_query.go
>  	} else if concept.Metadataxml.ValueMetadata.EncryptedType != "" {
What is the reason of the changes in this part?

2020-09-15 15:43 UTC, mickmis commented on wrappers/i2b2/crc_query.go
> +			//logrus.Warn("GetPatientSet: patient ", patient.PatientID, " misses dummy flag.")
Why commenting this log?

2020-09-15 15:43 UTC, mickmis commented on client/client.go
> +func ParseQueryString(queryString string) (panelsItemKeys [][]int64, panelsIsNot []bool, err error) {
If this function is needed elsewhere, it should be moved to another package rather than being made public from here. It can go in `util/client`.

2020-09-15 15:43 UTC, mickmis commented on client/client.go
> +			"set:" + fmt.Sprint(queryResult.PatientSetID),
You need to add the header column as well and remove the `"set:"` string.

2020-09-15 15:43 UTC, mickmis commented on client/client.go
> +					logrus.Debug("Caught exception from strconv %s: ", parsedErr)
This looks like an error that you cannot recover from. In that case you should log an error and return. Example from a few lines before:
```
logrus.Error("could not parse query integer multiplier: ", intMultiplierErr)
return nil, nil, intMultiplierErr
```

2020-09-15 15:43 UTC, mickmis commented on go.mod
> +replace github.com/ldsec/medco-unlynx => github.com/ldsec/medco-unlynx v0.3.2-0.20200414130428-b1239ae61d90
What is the reason for this? Why not setting directly the version below?

2020-09-15 15:43 UTC, mickmis commented on restapi/server/configure_medco_connector.go
> +	api.MedcoNodeGetCohortsHandler = medco_node.GetCohortsHandlerFunc(handlers.MedCoNodeGetCohortsHandler)
Add the comment line that specifies which HTTP path this covers like all the previous lines.

2020-09-15 15:43 UTC, mickmis commented on swagger/medco-connector.yml
> +      - in: "body"
Parameter should be put in the separate section to keep consistency with the rest of the definitions:

`$ref: "#/parameters/survivalAnalysisRequest"`

2020-09-15 15:43 UTC, mickmis commented on swagger/medco-connector.yml
> +        200:
Response should be put in the separate section to keep consistency with the rest of the file:

`$ref: "#/responses/survivalAnalysisResponse"`

2020-09-15 15:43 UTC, mickmis commented on swagger/medco-connector.yml
> +          description: "TODO not found"
Why TODO?

2020-09-15 15:43 UTC, mickmis commented on swagger/medco-connector.yml
> +        200:
Same comment as before, to be put in separate section with proper naming.

2020-09-15 15:43 UTC, mickmis commented on swagger/medco-connector.yml
> +        default:
Mistake: default is specified twice.

2020-09-15 15:43 UTC, mickmis commented on swagger/medco-connector.yml
> +        403:
More details in description: what could give a not authorized response?

2020-09-15 15:43 UTC, mickmis commented on swagger/medco-connector.yml
> +        - in: "body"
Same comment, to be put in the separate section.

2020-09-15 15:43 UTC, mickmis commented on swagger/medco-connector.yml
> +      summary: "Update cohorts list with a new or modified cohort"
"Add a new cohort or update an existing one"

2020-09-15 15:43 UTC, mickmis commented on swagger/medco-connector.yml
> +        default:
Mistake: again default response is present several times.

2020-09-15 15:43 UTC, mickmis commented on swagger/medco-connector.yml
> +          schema:
What is this "schema" in the response?

2020-09-15 15:43 UTC, mickmis commented on swagger/medco-connector.yml
> +        500:
What does that mean? What can the user do if he gets this error?

2020-09-15 15:43 UTC, mickmis commented on client/query_result.go
> +	PatientSetID int
Keep consistency and make the patientsetID an int64.

2020-09-15 15:43 UTC, mickmis commented on cmd/medco-cli-client/main.go
> +			ArgsUsage:   "[-r granularity] [-l limit] [-t type ] [-g groups]",
extra space

2020-09-15 15:43 UTC, mickmis commented on queryTools/queryTools.go
> +func init() {
The connection needs to be done the same way than it's done for the genomic annotations, check out `util/server/database.go` and `util/server/configuration.go`. Feel free to add more stuff there if needed.

2020-09-15 15:43 UTC, mickmis commented on queryTools/queryTools.go
> +package querytools
This file should be in a `server/cohorts` package. E.g. `server/cohorts/database.go`.

2020-09-15 15:43 UTC, mickmis commented on cohorts/common/cohort.go
> +package cohortscommon
This should in a `server/cohorts` package. E.g. `server/cohorts/model.go`.

2020-09-15 15:43 UTC, mickmis commented on queryTools/queryTools.go
> +	row := db.QueryRow(getPatientList, user_id, resultInstanceID)
What is this "getPatientList" variable?

2020-09-15 15:43 UTC, mickmis commented on queryTools/queryTools_test.go
> +package querytools
This should follow the other file.

2020-09-15 15:43 UTC, mickmis commented on queryTools/queryTools_test.go
> +	testDB, err := sql.Open("postgres", "host=localhost port=5432 user=postgres password=postgres dbname=medcoconnectorsrv0 sslmode=disable")
Check out `server/handlers/genomic_annotations_test.go` to do set the connection parameters the same way.

2020-09-15 15:43 UTC, mickmis commented on queryTools/queryTools_test.go
> +	if len(pList) != 228 {
Again this seems to be expecting some specific data. If you do so, it needs to be the default test data loaded by default in medco, and not data that is manually loaded separately. You should craft some small fake data and add it `medco-deployment` so that you can expect it here.

2020-09-15 15:43 UTC, mickmis commented on queryTools/sql.go
> +package querytools
Those declarations should go closer to where they are used, since they are only used once. 
I suggest each of those variables should be declared in the function where there are used.
And then this file can be removed.

2020-09-15 15:43 UTC, mickmis commented on server/explore_query_type.go
> +			PatientSet:  false,
Why is "PatientSet" always false ? That means that it is never needed. Here it should be set to "true" for the types of query where the patient set id should be returned.

2020-09-15 15:43 UTC, mickmis commented on server/explore_query_type.go
> +	// PatientSet  encodes if the patient set are needed further
This should be "PatientSetID" and not just "PatientSet", those are 2 different things.

2020-09-15 15:43 UTC, mickmis commented on server/handlers/medco_node.go
> +			PatientSetID:         float64(query.Result.PatientSetID),
This should not be a float. You probably need to update the swagger file to have an integer type.

2020-09-15 15:43 UTC, mickmis commented on server/handlers/medco_node.go
> +// MedCoNodeExploreQueryHandler handles /medco/node/explore/query API endpoint
Wrong comment.

2020-09-15 15:43 UTC, mickmis commented on server/handlers/medco_node.go
> +func MedCoNodePostCohortsHandler(params medco_node.PostCohortsParams, principal *models.User) middleware.Responder {
Missing comment.

2020-09-15 15:43 UTC, mickmis commented on server/handlers/medco_node.go
> +			Message: err.Error(),
The error message returned to the user of the API should give more context than just the underlying error.

2020-09-15 15:43 UTC, mickmis commented on server/handlers/medco_node.go
> +		return medco_node.NewGetCohortsNotFound()
Why a "not found" error if there are 0 cohorts? 0 cohorts is not an error.

2020-09-15 15:43 UTC, mickmis commented on server/handlers/medco_node.go
> +				CohortID:     float64(cohort.CohortId),
`CohortID` and `QueryID` should not be float.

2020-09-15 15:43 UTC, mickmis commented on server/handlers/medco_node.go
> +		return medco_node.NewPostCohortsDefault(500).WithPayload(&medco_node.PostCohortsDefaultBody{
This is not a server error, but a user input error. The code used should be 400.

2020-09-15 15:43 UTC, mickmis commented on server/handlers/medco_node.go
> +		return medco_node.NewPostCohortsDefault(500).WithPayload(&medco_node.PostCohortsDefaultBody{
Same comment.

2020-09-15 15:43 UTC, mickmis commented on server/handlers/medco_node.go
> +			Message: err.Error(),
Again, better error message needed.

2020-09-15 15:43 UTC, mickmis commented on server/handlers/medco_node.go
> +				return medco_node.NewPostCohortsInternalServerError()
Why do you use `NewPostCohortsInternalServerError()` here, and `NewPostCohortsDefault(500)` before ? This is not consistent, they are both 500 HTTP code.

2020-09-15 15:43 UTC, mickmis commented on server/handlers/medco_node.go
> +	return medco_node.NewPostCohortsOK().WithPayload("cohorts successfully updated")
This payload is wrong. The 200 OK returned code is enough to confirm to the user the operation was successful. If you want to add an additional message to give back to the user, you need to specify its JSON structure in the swagger definition file and populate it here.

2020-09-15 15:43 UTC, mickmis commented on deployment/Dockerfile
> +    I2B2_DB_NAME=i2b2medcosrv
Name should be i2b2medco and not i2b2medcosrv.

2020-09-15 15:43 UTC, mickmis commented on deployment/Dockerfile
> +    MC_DB_NAME=medcoconnectorsrv \
Name should be medcoconnector and not medcoconnectorsrv.

2020-09-15 15:43 UTC, mickmis commented on deployment/docker-compose.yml
> +      - MC_DB_NAME=medcoconnectorsrv
Name should be medcoconnector and not medcoconnectorsrv.

2020-09-15 15:43 UTC, mickmis commented on deployment/docker-compose.yml
> +      - I2B2_DB_NAME=i2b2medcosrv
Name should be i2b2medco and not i2b2medcosrv.

2020-09-15 15:43 UTC, mickmis commented on deployment/docker-entrypoint.sh
> +export SCHEMA="query_tools"
This variable name `SCHEMA` is too ambiguous.

2020-09-15 15:43 UTC, mickmis commented on deployment/docker-entrypoint.sh
> +#create the enum type
All those SQL structures and data should be defined in a separate file and loaded from here, to not clutter this script.

2020-09-15 15:43 UTC, mickmis commented on deployment/docker-entrypoint.sh
> +INSERT INTO query_tools.explore_query_results(
Sometime you use the variable `SCHEMA`, sometimes not, this is not consistent.

2020-09-15 15:43 UTC, mickmis commented on survival/client/access_token.go
> +package survivalclient
This code is duplicated. Delete this file and put this function alongside `utilclient.RetreiveAccessToken` in `client/security.go` as an helper function, and make it so that `ExecuteClientQuery` uses it as well.

2020-09-15 15:43 UTC, mickmis commented on survival/client/access_token.go
> +	if len(accessToken) > 0 {
It is also wrong here, the test should be done on `token`.

2020-09-15 15:43 UTC, mickmis commented on survival/client/cli.go
> +package survivalclient
This should go in a package `client/survivalanalysis`.

2020-09-15 15:43 UTC, mickmis commented on survival/client/explore_search.go
> +package survivalclient
This is not specific to the survival analysis, it should go in `client/search.go`. And be made available through the CLI by adding a corresponding function in `client/client.go`, plus the call from `cmd/medco-cli-client.go`.

2020-09-15 15:43 UTC, mickmis commented on survival/client/filter.go
> +package survivalclient
This should go in a package `client/survivalanalysis`.

2020-09-15 15:43 UTC, mickmis commented on survival/client/profiling.go
> +package survivalclient
This should go in a package `client/survivalanalysis`.

2020-09-15 15:43 UTC, mickmis commented on survival/client/survival_analysis.go
> +package survivalclient
This should go in a package `client/survivalanalysis`.

2020-09-15 15:43 UTC, mickmis commented on survival/client/survival_analysis_submit.go
> +package survivalclient
This should go in a package `client/survivalanalysis`.

2020-09-15 15:43 UTC, mickmis commented on survival/client/time_codes.go
> +package survivalclient
This should go in a package `client/survivalanalysis`.

2020-09-15 15:43 UTC, mickmis commented on survival/server/AKSwrapper.go
> +package survivalserver
This should go in a package `server/survivalanalysis`.

2020-09-15 15:43 UTC, mickmis commented on survival/server/clearDataSQLInterface.go
> +package survivalserver
This should go in a package `server/survivalanalysis` and be called `server/survivalanalysis/database.go`.

2020-09-15 15:43 UTC, mickmis commented on survival/server/exception_handler.go
> +package survivalserver
This should go in a package `server/survivalanalysis`.

2020-09-15 15:43 UTC, mickmis commented on survival/server/expansion.go
> +package survivalserver
This should probably be integrated in another file where it is used.

2020-09-15 15:43 UTC, mickmis commented on survival/server/survival_query.go
> +package survivalserver
This should go in a package `server/survivalanalysis`.

2020-09-15 15:43 UTC, mickmis commented on survival/server/survival_test.go
> +package survivalserver
This should go in a package `server/survivalanalysis`.
Also test should be done per file. If you have a source file named `survival_query.go`, the test file should be named `survival_query_test.go`. `expansion.go` -> `expansion_test.go`. Here you merged all the tests into one file, which is against the Go convention.

2020-09-15 15:43 UTC, mickmis commented on survival/server/survival_test.go
> +	db, err := sql.Open("postgres", "host=localhost port=5432 user=postgres password=postgres dbname=i2b2medcosrv0 sslmode=disable")
Same comments as for cohorts, database access needs to be consistent with the rest of the code, take the genomic annotations code as example.

2020-09-15 15:43 UTC, mickmis commented on wrappers/i2b2/crc_query.go
> +		var newFlag string
What does `newFlag` means? And why is it declared here? Looks like it can be declared when it is computed by unlynx.

2020-09-15 15:43 UTC, mickmis commented on wrappers/i2b2/crc_query.go
> +func NoAddedGetPatientSet(patientSetID string) (patientIDs []string, patientDummyFlags []string, err error) {
This is mostly a copy-paste of GetPatientSet. It is probably cleaner to add a flag to GetPatientSet instead of duplicating the code. Also the name of the function is confusing.

2020-09-15 15:43 UTC, mickmis commented on server/explore_query_logic.go
> +		encCount, ksCountTimers, err = unlynx.AggregateAndKeySwitchValue(q.ID, aggPatientFlags, string(q.Query.UserPublicKey))
What changed that made all those string casts necessary?

2020-09-15 15:43 UTC, mickmis commented on server/explore_query_logic.go
> +				itemKey = `\` + strings.ReplaceAll(*item.QueryTerm, "/", `\`)
What is this change? What made it necessary?

2020-09-15 15:43 UTC, mickmis commented on server/handlers/survival_analysis.go
> +		return survival_analysis.NewSurvivalAnalysisDefault(500).WithPayload(&survival_analysis.SurvivalAnalysisDefaultBody{Message: err.Error()})
Return the same message to API user that you are logging, i.e. with the additional `Query execution error :` to give some more context.

2020-09-15 15:43 UTC, mickmis commented on server/handlers/survival_analysis.go
> +	survivalAnalysisQuery.PrintTimers()
Where are those timers printed? They should not be in the console, but be returned in the response, just like for the explore query. Then it can be parsed by the client properly.

2020-09-15 15:43 UTC, mickmis commented on server/handlers/survival_analysis.go
> +	timers := make(map[string]float64, len(results.Timers))
To keep consistency, the timers implementation should be changed so that it is common between `ExploreQuery` and `SurvivalAnalysisQuery`. You can extract the timers implementation of `ExploreQuery` into a new `Timer` type, then embed it using composition in both `ExploreQuery` and `SurvivalAnalysisQuery`.

2020-09-15 15:43 UTC, mickmis commented on survival/client/survival_analysis.go
> +//for client !!!
What is this comment?

2020-09-15 15:43 UTC, mickmis commented on survival/server/getCodes.go
> +package survivalserver
No need for a separate file, this function can be defined in the file where it is used and be private.

2020-09-15 15:43 UTC, mickmis commented on survival/server/getCodes.go
> +//TODO use I2B2 ONT messaging
What does this mean?

2020-09-15 15:43 UTC, mickmis commented on survival/server/nice_error.go
> +func NiceError(err error) error {
Why is this used only once? Also the name is confusing.

2020-09-15 15:43 UTC, mickmis commented on survival/server/nice_error.go
> +package survivalserver
This function, if used, should not be declared here, but in `util/server`.

2020-09-15 15:43 UTC, mickmis commented on survival/server/sql.go
> +const sql1 string = `
Those variables names do not mean anything. Also those should be declared where they are used rather than a separate file.

2020-09-15 15:43 UTC, mickmis commented on survival/server/time_codes.go
> +package survivalserver
This should go in a package `server/survivalanalysis`. And the name of the file should reflect the struct defined: `time_codes_map.go`.

2020-09-15 15:43 UTC, mickmis commented on survival/server/time_codes.go
> +	//thoses maps are sinks, they can only grow, and once a value is inside,
and once a value is inside...?

2020-09-15 15:43 UTC, mickmis commented on survival/server/time_codes.go
> +type TimeCodesMap struct {
The struct should be declared at the top.

2020-09-15 15:43 UTC, mickmis commented on survival/server/time_codes.go
> +//NewTimeCodesMapWithCallback has the same purpose of NewTimeCodesMap, but return an error chan as the error can occur after the call of this function
There seem to be quite a bit of duplicated code here.

2020-09-15 15:43 UTC, mickmis commented on survival/server/time_codes.go
> +func (timeCodesMap *TimeCodesMap) getTagIDs() (err error) {
This should be called `retrieveTagIDs`, as you do not return them from the function.

2020-09-15 15:43 UTC, mickmis commented on survival/server/time_codes.go
> +	psqlQuery := tagQuery + ` WHERE time_path IN (` + paths + `)`
You should be passing the parameters to the Query function rather than craft the SQL string yourself. And also this should be in a separate function, in a file `server/survivalanalysis/database.go`.

2020-09-15 15:43 UTC, mickmis commented on survival/server/clearDataSQLInterface.go
> +	DirectI2B2, err = sql.Open("postgres", fmt.Sprintf("host=%s port=%s user=%s password=%s dbname=%s sslmode=disable", os.Getenv("I2B2_DB_HOST"), os.Getenv("I2B2_DB_PORT"), os.Getenv("I2B2_DB_USER"), o
Like commented previously, the connection to the database needs to be done in a consistent way, and only once (per database) in the code.

2020-09-15 15:43 UTC, mickmis commented on survival/server/expansion.go
> +func Expansion(timePoints []SqlTimePoint, timeLimit int) []SqlTimePoint {
The naming is confusing. Also does this need to be public? And I cannot find where this function is being used. If not used it should be deleted.

2020-09-15 15:43 UTC, mickmis commented on survival/server/getCohort.go
> +package survivalserver
This should be integrated in `server/survivalanalysis/database.go`.

2020-09-15 15:43 UTC, mickmis commented on survival/client/cli.go
> +func ClientSurvival(token string, patientSetID int, startConcept, startColumn, endConcept, endColumn, username, password string, disableTLSCheck bool) (err error) {
It's not clear to me if this functions makes the survival analysis query to all nodes?

2020-09-15 15:43 UTC, mickmis commented on survival/client/cli.go
> +	//TODO method in profiling.go
Just like the other existing client, the times/results should be output in CSV format, with the option of having it saved into a file. Code can be made common to be reused, check out `client/client.go`.

2020-09-15 15:43 UTC, mickmis commented on survival/client/cli.go
> +func parseAndEncryptQueryString(queryString string) (encPanels [][]string, panelsIsNot []bool, err error) {
Duplicated code. Not OK.

2020-09-15 15:43 UTC, mickmis commented on survival/client/explore_search.go
> +func NewExploreSearch(accessToken, path, Type string, disableTLSCheck bool) (search *ExploreSearch, err error) {
Lots of duplicated code here. Need to be put in common with what exists already.

2020-09-15 15:43 UTC, mickmis commented on survival/client/explore_search.go
> +	//TODO magic number
What is this?

2020-09-15 15:43 UTC, mickmis commented on survival/client/explore_search.go
> +	//TODO magic number
What is this?

2020-09-15 15:50 UTC, mickmis commented on survival/client/filter.go
> +		if *result.MedcoEncryption.Encrypted /* && *result.Leaf*/ {
Why is the second part left commented?

2020-09-16 07:35 UTC, mickmis commented on survival/client/survival_analysis.go
> +	//q.httpMedCoClient = client.New(transport, nil)
What is this commented line?

2020-09-16 07:36 UTC, mickmis commented on survival/client/survival_analysis.go
> +	//TODO magic number
What is this magic number?

2020-09-16 07:39 UTC, mickmis commented on survival/client/survival_analysis.go
> +func (clientSurvivalAnalysis *SurvivalAnalysis) addTimer(label string, since time.Time) (err error) {
As said in previous comment, timers implementation should be put in common with the explore query timers.

2020-09-16 07:41 UTC, mickmis commented on survival/server/AKSwrapper.go
> +func AKSgroups(queryID string, eventGroups EventGroups, targetPubKey string) (aksEventGroups EventGroups, time map[string]time.Duration, err error) {
Need documentation comment here. Notably what does AKS mean?

2020-09-16 07:42 UTC, mickmis commented on survival/server/AKSwrapper.go
> +	//TODO already tested
What does this mean?

2020-09-16 07:43 UTC, mickmis commented on survival/server/clearDataSQLInterface.go
> +	logrus.Print("SQL query : " + sql6)
Need a log level here, not just a print.

2020-09-16 07:44 UTC, mickmis commented on survival/server/exception_handler.go
> +//ExceptionHandler joins multiple parallel threads that can each returns an error
If this this is what the ExceptionHandler is doing, the name is confusing.

2020-09-16 07:44 UTC, mickmis commented on survival/server/exception_handler.go
> +//PushError push the error if th buffered channel is not full, does nothing else
pushes
the

2020-09-16 07:45 UTC, mickmis commented on survival/server/exception_handler.go
> +//WaitEndSignal waits until either the
either the?

2020-09-16 07:45 UTC, mickmis commented on survival/server/structs.go
> +	EventValueAgg     string //or kyber.point
or kyber.point?

2020-09-16 07:46 UTC, mickmis commented on survival/server/structs.go
> +	directAccessDB, err = NewSqlAccess("DIRECT_ACCESS_DB_")
As said before, DB connection needs to be done the same way everywhere in the codebase.

2020-09-16 07:47 UTC, mickmis commented on survival/server/structs.go
> +package survivalserver
This file seems to be containing a bit of everything. This probably should be better organized/documented/declared elsewhere, as we cannot understand from looking at this file what this is all about.

2020-09-16 07:51 UTC, mickmis commented on survival/server/subGroupExplore.go
> +package survivalserver
File should go to `server/survivanalysis`.

2020-09-16 07:51 UTC, mickmis commented on survival/server/subGroupExplore.go
> +//TODO this is redundant with query logic
Redundant?

2020-09-16 07:54 UTC, mickmis commented on survival/server/survival_query.go
> +			//TODO: pad for zero time
Is this needed?

2020-09-16 07:54 UTC, mickmis commented on survival/server/survival_query.go
> +	//Key Switch !!
Key switch?

2020-09-16 07:55 UTC, mickmis commented on survival/server/survival_query.go
> +func (q *Query) PrintTimers() {
Same comment as previously, timers should have one implementation.

2020-09-16 08:02 UTC, mickmis commented on survival/server/load_test_data.sh
> +#!/bin/bash -e
It probably makes more sense to have a smaller subset of this data loaded by default in the database through the docker entrypoint script.

2020-09-29 14:28 UTC, nfreundl commented on cmd/medco-cli-client/main.go
> +			ArgsUsage:   "[-r granularity] [-l limit] [-t type ] [-g groups]",
Where ?

2020-09-29 14:29 UTC, nfreundl commented on cohorts/common/cohort.go
> +package cohortscommon
Put in querytools package

2020-09-29 14:37 UTC, nfreundl commented on queryTools/queryTools.go
> +	row := db.QueryRow(getPatientList, user_id, resultInstanceID)
The SQL query string

2020-09-29 15:02 UTC, nfreundl commented on server/explore_query_logic.go
> +				itemKey = `\` + strings.ReplaceAll(*item.QueryTerm, "/", `\`)
I got an error because it expected backslashes, which were not added on clear concept path

2020-09-29 15:07 UTC, nfreundl commented on survival/server/sql.go
> +const sql1 string = `
They are shorter parts of one single query

2020-09-29 15:13 UTC, nfreundl commented on queryTools/queryTools_test.go
> +	if len(pList) != 228 {
Observation data for this test are in medco-deployment shell scripts

2020-09-29 19:44 UTC, nfreundl commented on survival/client/cli.go
> +	//TODO method in profiling.go
the CSV  writer is put in common. However, I haven't managed to use the same way to print results and timers in both clients, as they are quite different.
Also, I would like to use an input parameter file. What is the the most user-friendly way to do it when it is run in a container ?

2020-10-27 10:30 UTC, mickmis commented
New PR #47

2020-10-27 10:30 UTC, closed without merging