Range queries
lca1/medco-connector pull request #57
Opened 2020-11-25 11:47 UTC by f-marino

2020-11-30 16:56 UTC, mickmis requested changes
Looks good! Just an API modification that makes sense I think, and something that looks wrong in the makefile.

2020-11-30 16:56 UTC, mickmis commented on Makefile
> +	find connector/restapi/server/ -mindepth 1 -type d -delete
Doesn't this end up deleting the whole `/server` folder? `configure_medco_connector.go` needs to be kept and not deleted.

2020-11-30 16:56 UTC, mickmis commented on connector/swagger/medco-connector.yml
> +  /node/explore/search/concept-children:
For the API paths this is better I think (factoring a query parameter): 
- `.../concept?type=children`, `.../concept?type=self`
- `.../modifier?type=children`,  `.../modifier?type=self`

2020-12-01 08:28 UTC, f-marino commented on Makefile
> +	find connector/restapi/server/ -mindepth 1 -type d -delete
yep, this actually does the work. The second line delete all files in server/ except "configure_medco_connector.go", the third line delete all the directories in server/.

2020-12-01 09:19 UTC, mickmis commented on Makefile
> +	find connector/restapi/server/ -mindepth 1 -type d -delete
Ah I missed the directory part on second line. Good!

2020-12-01 13:31 UTC, f-marino commented on connector/swagger/medco-connector.yml
> +  /node/explore/search/concept-children:
Changed, just added the additional parameter in the body rather than in the URL. I think this PR is ready to be merged.

2020-12-01 19:25 UTC, mickmis approved these changes

2020-12-01 19:25 UTC, merged