added panel and sub group timing in SA
lca1/medco-connector pull request #91
Opened 2021-03-05 15:28 UTC by nfreundl

2021-03-09 10:11 UTC, JLRaisaro commented
I will! Thanks

> On 9 Mar 2021, at 10:45, nfreundl <notifications@github.com> wrote:
> 
> ﻿
> I2B2 query timing was not handled in API and sub group selection procedure.
> 
> This may also solve ldsec/glowing-bear-medco#121 . @JLRaisaro don't forget to check it really corrected the bug once this PR is closed
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/ldsec/medco/pull/91
> 
> Commit Summary
> 
> added panel and sub group timing in SA
> File Changes
> 
> M connector/client/survivalanalysis/cli.go (39)
> M connector/client/survivalanalysis/parameters.go (6)
> M connector/client/survivalanalysis/parameters_test.go (23)
> M connector/restapi/client/survival_analysis/survival_analysis_responses.go (23)
> M connector/restapi/models/panel.go (3)
> M connector/restapi/server/embedded_spec.go (9)
> M connector/restapi/server/operations/survival_analysis/survival_analysis.go (23)
> M connector/server/survivalanalysis/sub_group_explore.go (4)
> M connector/server/survivalanalysis/survival_query.go (15)
> M connector/swagger/medco-connector.yml (2)
> M test/survival_e2e_test_parameters.yaml (4)
> M test/survival_unit_test_parameters.yaml (5)
> Patch Links:
> 
> https://github.com/ldsec/medco/pull/91.patch
> https://github.com/ldsec/medco/pull/91.diff
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-03-10 09:58 UTC, mickmis requested changes
All good, minor comments. Also a conflict to resolve.

2021-03-10 09:58 UTC, mickmis commented on connector/client/survivalanalysis/cli.go
>  	logrus.Info("converting panels")
Even if not from this change, the logs here need more context, e.g. "Survival analysis <ID>: ..." 

Remember that when looking at the logs in a console everything is mixed up together. This makes debugging easier.

2021-03-10 09:58 UTC, mickmis commented on connector/server/survivalanalysis/survival_query.go
>  			logrus.Infof("I2B2 explore for subgroup %d", i)
More context for logs

2021-03-10 09:58 UTC, mickmis commented on connector/server/survivalanalysis/survival_query.go
>  				logrus.Errorf("during subgroup explore procedure: %s", err.Error())
you can create once the error to avoid repeating twice the error messages

2021-03-10 13:36 UTC, nfreundl commented on connector/server/survivalanalysis/survival_query.go
>  			logrus.Infof("I2B2 explore for subgroup %d", i)
From dev branches, all Info(f) Debug and Trace 's have prefixed with "Survival analysis: "

2021-03-11 08:15 UTC, mickmis approved these changes

2021-03-11 08:15 UTC, merged